### ISSUE TITLE
NX   Failed to process project graph

### ISSUE THREAD

**Issue by yonas** [tillywork/tillywork#27] opened 2024-05-22 01:06 UTC
```sh
❯ yarn dev
yarn run v1.22.19
$ nx run-many -t serve -p frontend backend

 NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.

Pass --verbose to see the stacktraces.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

yarn: 1.22.19
node: 21.7.1
OS: FreeBSD 14
Commit: 477d02eb

**Comment by MoShizzle** [comment] 2024-05-26 12:17
I'm unable to reproduce this, do you have the NX VS Code plugin? And if yes, do you see the packages correctly there?

**Comment by yonas** [comment] 2024-05-26 18:20
@MoShizzle No, I don't.

**Comment by yonas** [comment] 2024-05-26 22:49
@MoShizzle I was able to get past this error by upgrading all the nx dependencies to 19.1.0.

```diff
-        "@nx/cypress": "19.0.3",
-        "@nx/eslint": "19.0.3",
-        "@nx/eslint-plugin": "19.0.3",
-        "@nx/jest": "19.0.3",
-        "@nx/js": "19.0.3",
-        "@nx/nest": "19.0.3",
-        "@nx/node": "19.0.3",
-        "@nx/nuxt": "19.0.3",
-        "@nx/vite": "19.0.3",
-        "@nx/vue": "19.0.3",
-        "@nx/web": "19.0.3",
-        "@nx/webpack": "19.0.3",
+        "@nx/eslint": "19.1.0",
+        "@nx/eslint-plugin": "19.1.0",
+        "@nx/jest": "19.1.0",
+        "@nx/js": "19.1.0",
+        "@nx/nest": "19.1.0",
+        "@nx/node": "19.1.0",
+        "@nx/nuxt": "19.1.0",
+        "@nx/vite": "19.1.0",
+        "@nx/vue": "19.1.0",
+        "@nx/web": "19.1.0",
+        "@nx/webpack": "19.1.0",
```

**Comment by MoShizzle** [comment] 2024-05-28 08:54
@yonas I updated the project NX version, this should be fixed now

**Closed** 2024-05-28 08:54 UTC
